version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: Update

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
    rebase-strategy: auto
    commit-message:
      prefix: Update
