import assert from "node:assert/strict";
import { test } from "node:test";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { startChain, runScript, TEST_KEY } from "./common/bootstrap_chain.js";
import { testBootstrapBundle } from "./common/bootstrap_bundle.js";
import { loadBootstrapBundle } from "../scripts/lib/bootstrap_release.js";
import { configDigest } from "../scripts/lib/bootstrap_io.js";

test("Frozen bundle execution exports reproducible public evidence while preserving private recovery", { timeout: 150_000 }, async () => {
  const chain = await startChain();
  try {
    const bundle = await testBootstrapBundle(chain);
    const identity = path.join(String(bundle.config.chainId), (await loadBootstrapBundle(bundle.root)).genesisHash, configDigest(bundle.config));
    const privateRoot = path.join(chain.root, "private"), publicRoot = path.join(chain.root, "public");
    chain.statePath = path.join(privateRoot, identity, "state.json");
    const keyFile = path.join(chain.root, "private-key"), publicState = path.join(publicRoot, identity, "sourcedao-bootstrap-public-state.json");
    await writeFile(keyFile, TEST_KEY, { mode: 0o600 });
    const env = { SOURCE_DAO_BOOTSTRAP_PRIVATE_KEY: "", SOURCE_DAO_BOOTSTRAP_PRIVATE_KEY_FILE: keyFile,
      SOURCE_DAO_BUNDLE_DIR: bundle.root, SOURCE_DAO_USDB_RPC_URL: chain.url, SOURCE_DAO_NETWORK: "usdb-testnet-v0",
      SOURCE_DAO_BOOTSTRAP_PRIVATE_DIR: privateRoot, SOURCE_DAO_BOOTSTRAP_PUBLIC_DIR: publicRoot };
    const args: string[] = [];
    const checkArgs = ["check", "--bundle-dir", bundle.root, "--rpc-url", chain.url];
    const checkEnv = { SOURCE_DAO_BOOTSTRAP_PRIVATE_KEY: "", SOURCE_DAO_BOOTSTRAP_PRIVATE_KEY_FILE: "" };
    const preflight = await runScript("usdb_bootstrap_tools.ts", checkArgs, checkEnv).result;
    assert.equal(preflight.code, 0, preflight.output);
    const preflightReport = JSON.parse(preflight.output);
    assert.equal(preflightReport.ready_for_bootstrap, true);
    assert.equal(preflightReport.finalized, false);
    assert.equal(await chain.provider.getTransactionCount(chain.config.bootstrapAdminAddress), 0);
    let result = await runScript("usdb_bootstrap_tools.ts", ["bootstrap"], env, chain.root).result;
    assert.equal(result.code, 0, result.output);
    const finalizedCheck = await runScript("usdb_bootstrap_tools.ts", checkArgs, checkEnv).result;
    assert.equal(finalizedCheck.code, 0, finalizedCheck.output);
    assert.equal(JSON.parse(finalizedCheck.output).finalized, true);
    let privateState = JSON.parse(await readFile(chain.statePath, "utf8"));
    privateState.rpc_url = "https://private.invalid/?api-key=PRIVATE_SENTINEL";
    privateState.last_error = "PRIVATE_SENTINEL";
    privateState.config_path = "/private/PRIVATE_SENTINEL";
    privateState.extraRuntime = { privateKey: "PRIVATE_SENTINEL" };
    privateState.operations[0].details = "PRIVATE_SENTINEL";
    await writeFile(chain.statePath, JSON.stringify(privateState));
    const privateBytes = await readFile(chain.statePath, "utf8"), journalBytes = await readFile(`${chain.statePath}.transactions.json`, "utf8");
    const exportArgs: string[] = [];
    const readOnlyEnv = { ...env, SOURCE_DAO_BOOTSTRAP_PRIVATE_KEY_FILE: "" };
    result = await runScript("usdb_export_bootstrap_state.ts", exportArgs, readOnlyEnv, chain.root).result;
    assert.equal(result.code, 0, result.output);
    const bytes = await readFile(publicState, "utf8"), state = JSON.parse(bytes);
    assert.equal(state.record_schema, "sourcedao-bootstrap-public-state:v1");
    assert.equal(state.operations.length, 22);
    for (const forbidden of ["PRIVATE_SENTINEL", "raw_transaction", "rpc_url", "config_path", "artifacts_dir", TEST_KEY]) assert.equal(bytes.includes(forbidden), false, forbidden);
    const nonce = await chain.provider.getTransactionCount(chain.config.bootstrapAdminAddress);
    result = await runScript("usdb_export_bootstrap_state.ts", exportArgs, readOnlyEnv).result;
    assert.equal(result.code, 0, result.output); assert.equal(await readFile(publicState, "utf8"), bytes);
    result = await runScript("usdb_bootstrap_full.ts", args, env).result;
    assert.equal(result.code, 0, result.output);
    assert.equal(await chain.provider.getTransactionCount(chain.config.bootstrapAdminAddress), nonce);
    assert.equal(await readFile(chain.statePath, "utf8"), privateBytes);
    assert.equal(await readFile(`${chain.statePath}.transactions.json`, "utf8"), journalBytes);
    result = await runScript("usdb_validate_bootstrap.ts", [], readOnlyEnv, chain.root).result;
    assert.equal(result.code, 0, result.output);
    const defaultReport = JSON.parse(await readFile(path.join(publicRoot, identity, "sourcedao-bootstrap-validation.json"), "utf8"));
    assert.equal(defaultReport.mode, "strict");
    assert.equal(defaultReport.evidence.config_sha256, configDigest(bundle.config));
    const defaultReportPath = path.join(publicRoot, identity, "sourcedao-bootstrap-validation.json");
    const defaultReportBytes = await readFile(defaultReportPath, "utf8");
    await chain.provider.send("evm_mine", []);
    result = await runScript("usdb_validate_bootstrap.ts", [], readOnlyEnv).result;
    assert.equal(result.code, 0, result.output);
    assert.equal(await readFile(defaultReportPath, "utf8"), defaultReportBytes);
    result = await runScript("usdb_bootstrap_tools.ts", ["paths"], readOnlyEnv, chain.root).result;
    assert.equal(result.code, 0, result.output);
    const paths = JSON.parse(result.output);
    assert.equal(paths.state, chain.statePath); assert.equal(paths.publicState, publicState);
    assert.equal(paths.validation, defaultReportPath); assert.equal(paths.config, bundle.configPath);
    result = await runScript("usdb_bootstrap_full.ts", ["--network", "usdb-mainnet"], env).result;
    assert.equal(result.code, 1); assert.match(result.output, /differs from selected network/);
    assert.equal(await chain.provider.getTransactionCount(chain.config.bootstrapAdminAddress), nonce);
    result = await runScript("usdb_validate_bootstrap.ts", ["--bundle-dir", bundle.root, "--rpc-url", chain.url, "--state-file", publicState, "--strict", "--output", chain.reportPath]).result;
    assert.equal(result.code, 0, result.output);
    const validation = JSON.parse(await readFile(chain.reportPath, "utf8"));
    assert.equal("rpcUrl" in validation, false); assert.equal("artifactsDir" in validation, false);
    const acceptedBlock = validation.evidence.checkpoint.number;
    await chain.provider.send("evm_mine", []);
    result = await runScript("usdb_validate_bootstrap.ts", ["--bundle-dir", bundle.root, "--rpc-url", chain.url, "--state-file", publicState, "--strict", "--block", String(acceptedBlock), "--output", chain.reportPath]).result;
    assert.equal(result.code, 0, result.output);
    result = await runScript("usdb_bootstrap_full.ts", ["--bundle-dir", bundle.root, "--rpc-url", chain.url, "--state-file", publicState], env).result;
    assert.equal(result.code, 1); assert.match(result.output, /original private state/);
    assert.equal(await readFile(publicState, "utf8"), bytes);
    privateState.status = "running"; await writeFile(chain.statePath, JSON.stringify(privateState));
    result = await runScript("usdb_export_bootstrap_state.ts", exportArgs, readOnlyEnv).result;
    assert.equal(result.code, 1); assert.match(result.output, /completed full bootstrap/);
    assert.equal(await readFile(publicState, "utf8"), bytes);
    state.rpc_url = "PRIVATE_SENTINEL"; await writeFile(publicState, JSON.stringify(state));
    result = await runScript("usdb_validate_bootstrap.ts", ["--bundle-dir", bundle.root, "--rpc-url", chain.url, "--state-file", publicState, "--strict"]).result;
    assert.equal(result.code, 1); assert.match(result.output, /unexpected fields/);
    const networkPath = path.join(bundle.root, "network.json"), networkBytes = await readFile(networkPath, "utf8");
    const networkRecord = JSON.parse(networkBytes);
    networkRecord.artifacts.sourcedao_bootstrap_imported = networkRecord.artifacts.sourcedao_bootstrap;
    await writeFile(networkPath, JSON.stringify(networkRecord));
    await assert.rejects(loadBootstrapBundle(bundle.root), /Incomplete frozen source pair/);
    await writeFile(networkPath, networkBytes);
    await writeFile(bundle.configPath, `${await readFile(bundle.configPath, "utf8")}\n`);
    await assert.rejects(loadBootstrapBundle(bundle.root), /artifact hash mismatch/);
    result = await runScript("usdb_bootstrap_full.ts", args, env).result;
    assert.equal(result.code, 1); assert.match(result.output, /artifact hash mismatch/);
  } finally { await chain.close(); }
});
